name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      matrix:
        environment: [production, development]
        interface: [cli, fpm]
        version: [8.2]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.actor }}/php:${{ matrix.version }}-${{ matrix.interface }}-${{ matrix.environment }}
          file: ${{ matrix.version }}/Dockerfile
          labels: "org.opencontainers.image.source=https://github.com/${{ github.repository }}"
          build-args: PHP_VERSION=${{ matrix.version }},PHP_ENVIRONMENT=${{ matrix.environment }},PHP_INTERFACE=${{ matrix.interface }}
